name: SkyWars
main: co.mczone.skywars.SkyWars
version: 0.5.9 beta
depend: [Hive]
author: funkystudios
description: >
             MC Zone SkyWars
commands:
  matches:
    aliases: [games,arenas]
    description: View SkyWars matches
    default: true
  skywars:
    description: SkyWars administration
    default: true