name: MC Zone
version: 0.1b
author: funkystudios
main: co.mczone.MCZone
description: >
             MC Zone
commands:
  register:
    description: Register on MC Zone website
    usage: /register <password>
  ban:
    description: Ban an MC Zone player
    usage: /ban <player> <reason>
  unban:
    description: Unban an MC Zone player
    usage: /unban <player>
  tempban:
    description: Tempban an MC Zone player
    usage: /tempban <player> <time> <reason>
  kick:
    description: Kick an MC Zone player
    usage: /kick <player> <reason>
  list:
    description: List online players
    usage: /list
  hive:
    description: MC Zone admin command
    usage: /hive <args>