name: Ghost
main: co.mczone.ghost.Ghost
version: 0.1a
author: funkystudios
description: >
             MC Zone Ghost
commands:
  matches:
    aliases: [games]
    description: View Ghost matches
    default: true