name: Ghost
main: co.mczone.ghost.Ghost
version: 0.5.9 beta
depend: [Hive]
author: funkystudios
description: >
             MC Zone Ghost
commands:
  matches:
    aliases: [games,arenas]
    description: View Ghost matches
    default: true
  ghost:
    description: Ghost administration
    default: true