name: Ghost
main: co.mczone.ghost.Ghost
version: 0.6.0 beta
depend: [MC Zone]
author: funkystudios
description: >
             MC Zone Ghost
commands:
  arenas:
    aliases: [games,matches]
    description: View Ghost matches
    default: true
  ghost:
    description: Ghost administration
    default: true
  leave:
    description: Ghost leave command
    default: true
  help:
    description: Ghost help command
    default: true