name: Pets
version: 1.0
author: funkystudios
main: co.mczone.pets.Pets
depend: [MC Zone]
description: >
             MCZone Pets Plugin
commands:
  pet:
    aliases: [pets]
    description: MC Zone Pets
    default: true